### ISSUE TITLE
Layout issue with SURFnet logo

### ISSUE THREAD

**Issue by joostd** [SURFnet/tiqr-client-ios-surfnet#12]
See Screenshot: the SURFnet logo doesn't display correctly on an iPhone6 with iOS 10.0.2
![img_6226](https://cloud.githubusercontent.com/assets/668631/19238121/4e4acef8-8f00-11e6-96a1-bdfb06ee5ea5.PNG)

**Comment by 7hommay** [comment]
Het lijkt erop dat weergave zoom wordt gebruikt (Instellingen -> Beeldscherm en helderheid -> Weergavezoom). Ik heb geprobeerd het te reproduceren met en zonder weergave zoom op verschillende iPhones, maar dit is mij niet gelukt. @joostd Indien jij het wel kan reproduceren, zou je de stappen kunnen toelichten?

**Comment by joostd** [comment]
Lukt mij ook niet meer om te reproduceren (lig niet op iOS 10.3.3.
